
development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: ec2-54-243-233-96.compute-1.amazonaws.com
  database: d7e9v096gs9v7m 	
  username: quchweyktcyuce
  port: 5432
  password: WhtEEPExknihbhSg1wfUK_yAlq
  

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: ec2-54-243-233-96.compute-1.amazonaws.com
  database: d7e9v096gs9v7m 	
  username: quchweyktcyuce
  port: 5432
  password: WhtEEPExknihbhSg1wfUK_yAlq

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: ec2-54-243-233-96.compute-1.amazonaws.com
  database: d7e9v096gs9v7m 	
  username: quchweyktcyuce
  port: 5432
  password: WhtEEPExknihbhSg1wfUK_yAlq
